In [54]:
import pandas as pd

In [55]:
df=pd.read_excel('Nashville Housing Data for Data Cleaning.xlsx')

In [56]:
df.shape

(56477, 19)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56477 entries, 0 to 56476
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UniqueID         56477 non-null  int64
 1   ParcelID         56477 non-null  object
 2   LandUse          56477 non-null  object
 3   PropertyAddress  56448 non-null  object
 4   SaleDate         56477 non-null  datetime64[ns]
 5   SalePrice        56477 non-null  int64
 6   LegalReference   56477 non-null  object
 7   SoldAsVacant     56477 non-null  object
 8   OwnerName        25261 non-null  object
 9   OwnerAddress     26015 non-null  object
 10  Acreage          26015 non-null  float64
 11  TaxDistrict      26015 non-null  object
 12  LandValue        26015 non-null  float64
 13  BuildingValue    26015 non-null  float64
 14  TotalValue       26015 non-null  float64
 15  YearBuilt        24163 non-null  float64
 16  Bedrooms         24157 non-null  float64
 17  FullBath         24275 non-null  float64
 18  HalfBath         24144 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(2), object(8)
memory usage: 8.2+ MB

In [58]:
df.head()

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0

In [59]:
df.columns

Index(['UniqueID ', 'ParcelID', 'LandUse', 'PropertyAddress', 'SaleDate',
       'SalePrice', 'LegalReference', 'SoldAsVacant', 'OwnerName',
       'OwnerAddress', 'Acreage', 'TaxDistrict', 'LandValue', 'BuildingValue',
       'TotalValue', 'YearBuilt', 'Bedrooms', 'FullBath', 'HalfBath'],
      dtype='object')

In [60]:
df['UniqueID ']=df['UniqueID '].astype(str)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56477 entries, 0 to 56476
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UniqueID         56477 non-null  object
 1   ParcelID         56477 non-null  object
 2   LandUse          56477 non-null  object
 3   PropertyAddress  56448 non-null  object
 4   SaleDate         56477 non-null  datetime64[ns]
 5   SalePrice        56477 non-null  int64
 6   LegalReference   56477 non-null  object
 7   SoldAsVacant     56477 non-null  object
 8   OwnerName        25261 non-null  object
 9   OwnerAddress     26015 non-null  object
 10  Acreage          26015 non-null  float64
 11  TaxDistrict      26015 non-null  object
 12  LandValue        26015 non-null  float64
 13  BuildingValue    26015 non-null  float64
 14  TotalValue       26015 non-null  float64
 15  YearBuilt        24163 non-null  float64
 16  Bedrooms         24157 non-null  float64
 17  FullBath         24275 non-null  float64
 18  HalfBath         24144 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(9)
memory usage: 8.2+ MB

In [62]:
##df['YearBuilt']=df['YearBuilt'].astype('int64')

In [63]:
df['SaleDate']=df['SaleDate'].astype(str)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56477 entries, 0 to 56476
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UniqueID         56477 non-null  object
 1   ParcelID         56477 non-null  object
 2   LandUse          56477 non-null  object
 3   PropertyAddress  56448 non-null  object
 4   SaleDate         56477 non-null  object
 5   SalePrice        56477 non-null  int64
 6   LegalReference   56477 non-null  object
 7   SoldAsVacant     56477 non-null  object
 8   OwnerName        25261 non-null  object
 9   OwnerAddress     26015 non-null  object
 10  Acreage          26015 non-null  float64
 11  TaxDistrict      26015 non-null  object
 12  LandValue        26015 non-null  float64
 13  BuildingValue    26015 non-null  float64
 14  TotalValue       26015 non-null  float64
 15  YearBuilt        24163 non-null  float64
 16  Bedrooms         24157 non-null  float64
 17  FullBath         24275 non-null  float64
 18  HalfBath         24144 non-null  float64
dtypes: float64(8), int64(1), object(10)
memory usage: 8.2+ MB

In [65]:
df.head()

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0

In [66]:
df['SalesYear']=df['SaleDate'].str.split('-',expand=True)[0]

In [67]:
df['SalesMonth']=df['SaleDate'].str.split('-',expand=True)[1]

In [68]:
df['SalesDay']=df['SaleDate'].str.split('-',expand=True)[2]

In [69]:
df.head()

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,SalesYear,SalesMonth,SalesDay
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE",2013-04-09,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0,2013,04,09
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE",2014-06-10,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0,2014,06,10
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE",2016-09-26,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0,2016,09,26
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE",2016-01-29,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0,2016,01,29
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE",2014-10-10,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0,2014,10,10

In [70]:
df.drop(columns=['SaleDate'],inplace=True)

In [71]:
df['1']=df['PropertyAddress'].str.split(',',expand=True)[0]

In [72]:
df['2']=df['PropertyAddress'].str.split(',',expand=True)[1]

In [73]:
df.rename(columns={'1':'PropertyStreet'},inplace=True)

In [74]:
df.rename(columns={'2':'PropertyCity'},inplace=True)

In [75]:
df.drop(columns=['PropertyAddress'], inplace=True)

In [76]:
df.head()

,UniqueID,ParcelID,LandUse,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,SalesYear,SalesMonth,SalesDay,PropertyStreet,PropertyCity
0,2045,007 00 0 125.00,SINGLE FAMILY,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0,2013,04,09,1808 FOX CHASE DR,GOODLETTSVILLE
1,16918,007 00 0 130.00,SINGLE FAMILY,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0,2014,06,10,1832 FOX CHASE DR,GOODLETTSVILLE
2,54582,007 00 0 138.00,SINGLE FAMILY,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0,2016,09,26,1864 FOX CHASE DR,GOODLETTSVILLE
3,43070,007 00 0 143.00,SINGLE FAMILY,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0,2016,01,29,1853 FOX CHASE DR,GOODLETTSVILLE
4,22714,007 00 0 149.00,SINGLE FAMILY,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0,2014,10,10,1829 FOX CHASE DR,GOODLETTSVILLE

In [77]:
df.columns

Index(['UniqueID ', 'ParcelID', 'LandUse', 'SalePrice', 'LegalReference',
       'SoldAsVacant', 'OwnerName', 'OwnerAddress', 'Acreage', 'TaxDistrict',
       'LandValue', 'BuildingValue', 'TotalValue', 'YearBuilt', 'Bedrooms',
       'FullBath', 'HalfBath', 'SalesYear', 'SalesMonth', 'SalesDay',
       'PropertyStreet', 'PropertyCity'],
      dtype='object')

In [78]:
pd.options.display.max_columns=100

In [79]:
df.head()

,UniqueID,ParcelID,LandUse,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,SalesYear,SalesMonth,SalesDay,PropertyStreet,PropertyCity
0,2045,007 00 0 125.00,SINGLE FAMILY,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0,2013,04,09,1808 FOX CHASE DR,GOODLETTSVILLE
1,16918,007 00 0 130.00,SINGLE FAMILY,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0,2014,06,10,1832 FOX CHASE DR,GOODLETTSVILLE
2,54582,007 00 0 138.00,SINGLE FAMILY,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0,2016,09,26,1864 FOX CHASE DR,GOODLETTSVILLE
3,43070,007 00 0 143.00,SINGLE FAMILY,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0,2016,01,29,1853 FOX CHASE DR,GOODLETTSVILLE
4,22714,007 00 0 149.00,SINGLE FAMILY,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0,2014,10,10,1829 FOX CHASE DR,GOODLETTSVILLE

In [80]:
df["Owner'Street"]=df['OwnerAddress'].str.split(',',expand=True)[0]

In [81]:
df["Owner'sCity"]=df['OwnerAddress'].str.split(',',expand=True)[1]

In [82]:
df["Owner'sLAst level"]=df['OwnerAddress'].str.split(',',expand=True)[2]

In [83]:
df.drop(columns=['OwnerAddress'],inplace=True)

In [84]:
df.head()

,UniqueID,ParcelID,LandUse,SalePrice,LegalReference,SoldAsVacant,OwnerName,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath,SalesYear,SalesMonth,SalesDay,PropertyStreet,PropertyCity,Owner'Street,Owner'sCity,Owner'sLAst level
0,2045,007 00 0 125.00,SINGLE FAMILY,240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0,2013,04,09,1808 FOX CHASE DR,GOODLETTSVILLE,1808 FOX CHASE DR,GOODLETTSVILLE,TN
1,16918,007 00 0 130.00,SINGLE FAMILY,366000,20140619-0053768,No,"BONER, CHARLES & LESLIE",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0,2014,06,10,1832 FOX CHASE DR,GOODLETTSVILLE,1832 FOX CHASE DR,GOODLETTSVILLE,TN
2,54582,007 00 0 138.00,SINGLE FAMILY,435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0,2016,09,26,1864 FOX CHASE DR,GOODLETTSVILLE,1864 FOX CHASE DR,GOODLETTSVILLE,TN
3,43070,007 00 0 143.00,SINGLE FAMILY,255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0,2016,01,29,1853 FOX CHASE DR,GOODLETTSVILLE,1853 FOX CHASE DR,GOODLETTSVILLE,TN
4,22714,007 00 0 149.00,SINGLE FAMILY,278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0,2014,10,10,1829 FOX CHASE DR,GOODLETTSVILLE,1829 FOX CHASE DR,GOODLETTSVILLE,TN

In [85]:
df['SoldAsVacant'].unique()

array(['No', 'N', 'Yes', 'Y'], dtype=object)

In [97]:
df['SoldAsVacant']=df['SoldAsVacant'].replace("^'N'$","'No'",regex=True)

In [98]:
df['SoldAsVacant']=df['SoldAsVacant'].replace("^'Y'$","'Yes'",regex=True)

In [99]:
df['SoldAsVacant'].unique()

array(['No', 'N', 'Yes', 'Y'], dtype=object)

In [50]:
df.columns

Index(['UniqueID ', 'ParcelID', 'LandUse', 'SalePrice', 'LegalReference',
       'SoldAsVacant', 'OwnerName', 'Acreage', 'TaxDistrict', 'LandValue',
       'BuildingValue', 'TotalValue', 'YearBuilt', 'Bedrooms', 'FullBath',
       'HalfBath', 'SalesYear', 'SalesMonth', 'SalesDay', 'PropertyStreet',
       'PropertyCity', 'Owner'Street', 'Owner'sCity', 'Owner'sLAst level'],
      dtype='object')